exports.up = knex => knex.schema.createTable('rentals', table => {
  table.increments('id').primary()
  table.timestamp('created_at').defaultTo(knex.fn.now())
  table.string('first_name').notNullable()
  table.string('last_name')
  table.string('email').notNullable()
  table.integer('phone_number')
  table.string('address_1')
  table.string('address_2')
  table.boolean('driver_needed').notNullable().defaultTo('true')
  table.date('rental_date').notNullable()
  table.time('start_rental').notNullable()
  table.time('end_rental').notNullable()
})

exports.down = knex => knex.schema.dropTable('rentals')
